### PR TITLE
This pull request allows building and running on aarch64 systems

### PR DESCRIPTION
**Pull request by hyperwidget**
With a few minor changes to things that are x86 specific we can get this to build and run on arm64 systems

### CODE REVIEW

**Comment by val-antonescu** [comment]
Without looking at the code I see 2 open questions here. One is how useful would it be for our scientific community to be able to run bowtie on an arm64 system. And second, which I know is mostly our problem though, is how are we going to offer support in the future?
I will leave this open to discussion for now because it is after all a novel and interesting proposal.

thanks,
Val

**Comment by BenLangmead** [comment]
Just giving this request a nudge since we just did something similar for Bowtie 2, including the addition of Travis-based tests for ARM, and seems very possible we could do the same in Bowtie in next release

**Comment by junaruga** [comment]
Hello. I sent following pull-request related to running aarch64 systems.

Add aarch64, ppc64le and s390x cases to Travis CI https://github.com/BenLangmead/bowtie/pull/102

**Comment by junaruga** [comment]
@hyperwidget  now you can build bowtie on aarch64 systems, and bowtie latest version 1.3.0's aarch64 binary was released. Maybe you can close this PR.

**Pull request closed without merging**
